version: '3'
services:
  node_app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
